### ISSUE TITLE
Where place we can install makefile

### ISSUE THREAD

**Issue by yona-asael** [robsoncouto/gm328a_rev_eng#1]
I had a problem because i want to install the makefile but i get confusion, do you have a tutorial or example the best way to install it?

**Comment by robsoncouto** [comment]
Hi, do you want to compile the firmware? If you use linux you have to install avr-gcc and avr-libc. Then you can run the makefile from the folder using a terminal by using the command "make". I have no idea how to do this using windows. 
[This tutorial](https://blog.podkalicki.com/how-to-compile-and-burn-the-code-to-avr-chip-on-linuxmacosxwindows/) that may help you.

**Comment by yona-asael** [comment]
Ok thank you, i saw the tutorial and it works :3 i like it, thank you now i can have to diferent chips one for test my compoents the other for play tetris if my smathphone is run out of battery
